function [curve_paramters, converged, chisquare, iteration_count, time]...
    = CPUfit(...
    data,...
    sigma,...
    max_n_iterations,...
    initial_parameters,...
    parameters_to_fit,...
    modelID,...
    estimatorID,...
    tolerance,...
    user_info)

%% conficure parameters
n_points = length(sigma);
n_fits = numel(data)/n_points;
n_parameters = length(parameters_to_fit);

%% convert types of vectors
if ~isa(data, 'single')
    data = single(data);
end
if ~isa(sigma, 'single')
    sigma = single(sigma);
end
if ~isa(initial_parameters, 'single')
    initial_parameters = single(initial_parameters);
end
if ~isa(parameters_to_fit, 'int32')
    parameters_to_fit = int32(parameters_to_fit);
end
if ~isa(user_info, 'int32')
    user_info = int32(user_info);
end

%% run GpuFit
tic;
[curve_paramters, converged, chisquare, iteration_count] ...
    = CpuFitMex(...
    data,...
    sigma,...
    n_fits,...
    n_points,...
    tolerance,...
    max_n_iterations,...
    estimatorID,...
    initial_parameters,...
    parameters_to_fit,...
    modelID,...
    n_parameters,...
    user_info,...
    size(user_info,2));
time = toc;

end
