function [curve_paramters, converged, chisquare, iteration_count, times, time]...
    = CpuFit_profile(...
    data,...
    sigma,...
    max_n_iterations,...
    initial_parameters,...
    parameters_to_fit,...
    modelID,...
    estimatorID,...
    tolerance)

%% conficure parameters
n_points = length(sigma);
n_fits = numel(data)/n_points;
n_parameters = length(parameters_to_fit);

%% convert types of vectors
if ~isa(data, 'single')
    data = single(data);
end
if ~isa(sigma, 'single')
    sigma = single(sigma);
end
if ~isa(initial_parameters, 'single')
    initial_parameters = single(initial_parameters);
end
if ~isa(parameters_to_fit, 'int32')
    parameters_to_fit = int32(parameters_to_fit);
end

%% run GpuFit
tic;
[curve_paramters, converged, chisquare, iteration_count, times] ...
    = CpuFit_profileMex(...
    data,...
    sigma,...
    n_fits,...
    n_points,...
    tolerance,...
    max_n_iterations,...
    estimatorID,...
    initial_parameters,...
    parameters_to_fit,...
    modelID,...
    n_parameters);
time = toc;

end
