function [parameters, info, chi_square, time]...
    = GPULMFit(...
    data,...
    estimator_id,...
    initial_parameters,...
    fit_size)

%% configure parameters
n_fits = numel(data)/fit_size/fit_size;

%% convert types of vectors
if ~isa(data, 'single')
    data = single(data);
end

%% run GPU-LMFit
GPU_Block_Size = 128;   %original: 128 
GPU_Grid_Size = n_fits;   %original: 1024 

reshaped_data = single(reshape(data,1,fit_size*fit_size*n_fits));

reshaped_initial_parameters = single(reshape(initial_parameters,1,numel(initial_parameters)));

tic
[parameters, info, chi_square] = gpulmfit(...
    reshaped_data,...
    fit_size,...
    reshaped_initial_parameters,...
    abs(estimator_id-1),...
    1,...
    0,...
    GPU_Block_Size,...
    GPU_Grid_Size);
time = toc;

end
