function [parameters, info, time]...
    = GPULMFit(...
    data,...
    estimator_id,...
    initial_width,...
    fit_size)

%% configure parameters
n_fits = numel(data)/fit_size/fit_size;

%% convert types of vectors
if ~isa(data, 'single')
    data = single(data);
end

%% run GPU-LMFit
GPU_Block_Size = 128;   %original: 128 
GPU_Grid_Size = 50000;   %original: 1024 
reshaped_data = single(reshape(data,1,fit_size*fit_size*n_fits));
tic
[parameters, info] = GPU2DGaussFit(...
    reshaped_data,...
    fit_size,...
    initial_width,...
    abs(estimator_id-1),...
    1,...
    0,...
    GPU_Block_Size,...
    GPU_Grid_Size);
time = toc;

end
